<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f3c3434f-2644-42fa-bf8e-65c9053f1e96</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Alkanzi.Auditable.EntityFrameworkCore\Alkanzi.Auditable.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Alkanzi.Erp.Domain\Alkanzi.Erp.Domain.csproj" />
    <ProjectReference Include="..\..\src\Alkanzi.Erp.Application\Alkanzi.Erp.Application.csproj" />
    <ProjectReference Include="..\..\src\Alkanzi.Erp.DataAccess\Alkanzi.Erp.DataAccess.csproj" />
  </ItemGroup>

</Project>
